// Generated by gencpp from file test/sercli.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SERCLI_H
#define TEST_MESSAGE_SERCLI_H

#include <ros/service_traits.h>


#include <test/sercliRequest.h>
#include <test/sercliResponse.h>


namespace test
{

struct sercli
{

typedef sercliRequest Request;
typedef sercliResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sercli
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::sercli > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::test::sercli&) { return value(); }
};

template<>
struct DataType< ::test::sercli > {
  static const char* value()
  {
    return "test/sercli";
  }

  static const char* value(const ::test::sercli&) { return value(); }
};


// service_traits::MD5Sum< ::test::sercliRequest> should match
// service_traits::MD5Sum< ::test::sercli >
template<>
struct MD5Sum< ::test::sercliRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::sercli >::value();
  }
  static const char* value(const ::test::sercliRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::sercliRequest> should match
// service_traits::DataType< ::test::sercli >
template<>
struct DataType< ::test::sercliRequest>
{
  static const char* value()
  {
    return DataType< ::test::sercli >::value();
  }
  static const char* value(const ::test::sercliRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::sercliResponse> should match
// service_traits::MD5Sum< ::test::sercli >
template<>
struct MD5Sum< ::test::sercliResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::sercli >::value();
  }
  static const char* value(const ::test::sercliResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::sercliResponse> should match
// service_traits::DataType< ::test::sercli >
template<>
struct DataType< ::test::sercliResponse>
{
  static const char* value()
  {
    return DataType< ::test::sercli >::value();
  }
  static const char* value(const ::test::sercliResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SERCLI_H
